name: RestaurantBookingApp
on:
  pull_request:
    branches: [ test ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: restaurant booking app
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        docker build -t ${{ secrets.HEROKU_APP_NAME }} .
        docker tag ${{ secrets.HEROKU_APP_NAME }} registry.heroku.com
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
